# -*- coding: utf-8 -*-
"""project1.jl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYHuQa0gPqmdP4pcu1J20vlbtCNXUS_w
"""

# import Pkg
# Pkg.add("JuMP"); Pkg.add("HiGHS"); Pkg.add("Plots"); Pkg.add("CSV"); Pkg.add("DataFrames")

using JuMP
using HiGHS
ENV["GKSwstype"] = "nul"
using Plots
using CSV
using DataFrames

# Create a new optimization model
model = Model(HiGHS.Optimizer)

n_gen = 3
n_nodes = 2
n_lines = 1
n_demand = 2
t_steps = 24

# Data
g_opex = [30, 20, 40]
g_op_max = [100, 50, 500] # Increased capacity for generator 3 to ensure feasibility

incidence = [1, -1]


f_lim = 1000 # 1 GW line limit
demand = [
  [60, 60, 50, 50, 70, 90, 110, 120, 120, 110, 100, 100, 100, 90, 110, 130, 150, 140, 130, 120, 100, 80, 70, 60],
  [150, 140, 130, 120, 150, 180, 200, 220, 210, 200, 190, 180, 170, 160, 180, 200, 230, 250, 240, 220, 190, 170, 160, 150]
  ]

# Define variables
@variable(model, g[1:n_gen, 1:t_steps] >= 0)
@variable(model, -1 * f_lim <= f[1:n_lines, 1:t_steps] <= f_lim)


# Define the objective function
@objective(model, Min, sum(g_opex[i]*g[i,t] for i=1:n_gen, t=1:t_steps))

# Define constraints
@constraint(model, gen_op_lim[i=1:n_gen,t=1:t_steps], g[i,t]<= g_op_max[i])

@constraint(model,
  demand_balance_n1[t=1:t_steps],
  g[1,t] + g[2,t] - demand[1][t] + f[1,t] == 0
  )

@constraint(model,
  demand_balance_n2[t=1:t_steps],
  g[3,t] - demand[2][t] - f[1,t] == 0
  )

# Solve the optimization problem
optimize!(model)

# Check if the solution is optimal
if termination_status(model) == MOI.OPTIMAL
    println("Optimization successful!")
    println("Optimal objective value: ", objective_value(model))

    # Extract and print generator outputs
    global g_values = value.(g)
    println("\nGenerator outputs (g):")
    for i in 1:n_gen
        println("  Generator $(i): ", g_values[i,:])
    end

    # Extract and print line flows
    global f_values = value.(f)
    println("\nLine flows (f):")
    for i in 1:n_lines
        println("  Line $(i): ", f_values[i,:])
    end

else
    println("Optimization failed or not optimal: ", termination_status(model))
end

"""### Generator Outputs Plots"""

time_steps = 1:t_steps

for i in 1:n_gen
    p = plot(time_steps, g_values[i,:], label="Generator $(i) Output", xlabel="Time Step", ylabel="Generation (MW)", title="Generator $(i) Output Over Time")
    display(p)
end

x_up = [vcat(repeat(g_op_max, outer=t_steps), repeat([f_lim], outer=t_steps))]

f_lim

# ── Settings ─────────────────────────────────────────────────────
prob_num = 6            # 1 | 2 | 3 | 4 | 5
alg      = "kelley"    # "kelley" | "subgradient" | "both"

out_dir  = joinpath(@__DIR__, "problem$(prob_num)")
mkpath(out_dir)

# ── Problem definitions ──────────────────────────────────────────
# Default: no indexed balance constraints unless the active problem sets them.
balance_indices = nothing
balance_oracle  = nothing
balance_kind    = :eq

if prob_num == 1
    n    = 1 # number of dimensions
    x_lb = [-0.5] # Lower bound
    x_ub = [1.0]  # Upper Bound
    functionAndGradient(x) = (x'x, 2*x) # function definition & gradient definition

elseif prob_num == 2
    n = 1
    x_lb = [1.0]
    x_ub = [2.0]
    functionAndGradient(x) = (x'x, 2*x)

elseif prob_num == 3
    n    = 1
    x_lb = [-0.5]
    x_ub = [2.0]
    function functionAndGradient(x)
        x_value = x[1]
        vals    = [exp(-x_value), x_value, x_value^2]       # the three component values
        i       = argmax(vals)                               # index of active component
        grads   = [-exp(-x_value), 1.0, 2.0*x_value]        # gradients of e^-x, x, x²
        return (vals[i], [grads[i]])                         # return scalar f and length-1 gradient
    end

elseif prob_num == 4
    error("Problem 4 not yet implemented")

elseif prob_num == 5
    error("Problem 5 not yet implemented")

elseif prob_num == 6
    # Decision vector x layout (length n):
    #   generation g[i,t]        → x[g_idx(i,t)]    for i=1:n_gen,   t=1:t_steps
    #   line flow f[l,t]         → x[f_idx(l,t)]    for l=1:n_lines, t=1:t_steps
    #   balance epigraph θ[nd,t] → x[epi_idx(nd,t)] for nd=1:n_nodes,t=1:t_steps
    n_epi = n_nodes * t_steps
    n     = t_steps*n_gen + t_steps*n_lines + n_epi

    g_idx(i, t)    = (t-1)*n_gen   + i
    f_idx(l, t)    = t_steps*n_gen + (t-1)*n_lines + l
    epi_idx(nd, t) = t_steps*n_gen + t_steps*n_lines + (t-1)*n_nodes + nd

    # Bounds: gens in [0, g_op_max], flows in [-f_lim, f_lim], epigraphs ≥ 0
    x_lb = zeros(n)
    x_ub = Vector{Float64}(undef, n)
    for i in 1:n_gen
        for t in 1:t_steps
            x_ub[g_idx(i, t)] = g_op_max[i]
        end
    end
    for l in 1:n_lines
        for t in 1:t_steps
            x_lb[f_idx(l, t)] = -f_lim
            x_ub[f_idx(l, t)] =  f_lim
        end
    end
    for nd in 1:n_nodes
        for t in 1:t_steps
            x_ub[epi_idx(nd, t)] = 1e8   # epigraph UB: just needs to be large
        end
    end

    # Linear objective: generator cost + large penalty on balance epigraphs
    BAL_PENALTY = 1e6
    cost = zeros(n)
    for i in 1:n_gen
        for t in 1:t_steps
            cost[g_idx(i, t)] = g_opex[i]
        end
    end
    for nd in 1:n_nodes
        for t in 1:t_steps
            cost[epi_idx(nd, t)] = BAL_PENALTY
        end
    end

    functionAndGradient(x) = (cost' * x, copy(cost))

    # Indexed demand-balance constraints
    #   node 1, t : g[1,t] + g[2,t] + f[1,t] − demand[1][t] == 0
    #   node 2, t : g[3,t]          − f[1,t] − demand[2][t] == 0
    balance_indices = [(nd, t) for nd in 1:n_nodes for t in 1:t_steps]
    function balance_oracle(x, idx)
        (nd, t) = idx
        gv = zeros(n)
        if nd == 1 #node 1
            v = x[g_idx(1,t)] + x[g_idx(2,t)] + x[f_idx(1,t)] - demand[1][t] # Net injections at node 1
            gv[g_idx(1,t)] =  1.0 # gradients of net injections
            gv[g_idx(2,t)] =  1.0
            gv[f_idx(1,t)] =  1.0
        else  # nd == 2
            v = x[g_idx(3,t)] - x[f_idx(1,t)] - demand[2][t] # net injections at node 2
            gv[g_idx(3,t)] =  1.0
            gv[f_idx(1,t)] = -1.0 # negative injection due to withdraw from line 1
        end
        return (v, gv, epi_idx(nd, t))
    end
    balance_kind = :eq
end

# ── Save outputs ─────────────────────────────────────────────────
function save_outputs(X, F, G, LB, UB, x_best, k, cpu_time, alg)
    # Summary table
    CSV.write(joinpath(out_dir, "summary_$(alg).csv"),
        DataFrame(Algorithm=[alg], FinalObjective=[UB[end]], FinalGap=[UB[end]-LB[end]],
                  Iterations=[k], CPUTime_s=[round(cpu_time, digits=4)]))

    # Iteration data CSV
    CSV.write(joinpath(out_dir, "iteration_data_$(alg).csv"),
        DataFrame(Iteration=1:k, LowerBound=LB, UpperBound=UB, OracleValue=F, Gap=UB.-LB))

    # Convergence plot: UB, LB, gap vs iteration (skip k=1: LB initialised to -1e6)
    ks = 2:k
    p_conv = plot(ks, UB[2:end], label="UB", lw=2, xlabel="Iteration", ylabel="Objective",
                  title="Convergence — $(titlecase(alg)) P$(prob_num)", legend=:topright)
    plot!(p_conv, ks, LB[2:end],             label="LB",  lw=2)
    plot!(p_conv, ks, (UB .- LB)[2:end],     label="Gap", lw=2, linestyle=:dash)
    savefig(p_conv, joinpath(out_dir, "convergence_$(alg).png"))
    Plots.closeall()

    # Univariate function + cutting planes plot (n=1 only)
    if n == 1
        x_range = range(x_lb[1] - 0.1, x_ub[1] + 0.1, length=200)
        p = plot(x_range, [functionAndGradient([xi])[1] for xi in x_range],
                 label="f(x)", lw=2, color=:black,
                 xlabel="x", ylabel="f(x)", title="$(titlecase(alg)) — P$(prob_num)",
                 legend=:outertopright, size=(800, 400))
        for i in eachindex(F)
            plot!(p, x_range, [F[i] + G[i]' * ([xi] .- X[i]) for xi in x_range],
                  label=false, linestyle=:dash, alpha=0.5)
        end
        scatter!(p, [xi[1] for xi in X], F, label="Test points", color=:red, marker=:circle)
        for i in eachindex(X)
            annotate!(p, X[i][1], F[i] + 0.15, text("$i", 8, :center, :red))
        end
        redirect_stderr(devnull) do
            scatter!(p, [x_best[1]], [UB[end]], label="x*", color=:green, marker=:star5, ms=8)
        end
        savefig(p, joinpath(out_dir, "function_plot_$(alg).png"))
        Plots.closeall()
    end

    println("Saved to $(out_dir)/  |  f(x*) = $(UB[end])  gap = $(UB[end]-LB[end])  k = $k")
end

# ── Kelley cutting-plane algorithm ──────────────────────────────
# Optional kwargs let us add indexed balance-style epigraph constraints as
# cutting planes.  The epigraph *variables themselves* live inside x (baked
# into the problem definition, e.g. problem 6), so the objective is untouched.
#
#   balance_indices : iterable of identifiers, e.g. [(node, t) for node in 1:n_nodes, t in 1:t_steps]
#   balance_oracle  : function (x, idx) -> (value, gradient, j_epi)
#                       value     = residual c_idx(x)
#                       gradient  = ∇c_idx(x)           (length n)
#                       j_epi     = index into x of the epigraph variable for idx
#   balance_kind    : :eq for c(x) == 0  (cuts on both +c and -c; drives x[j] → 0)
#                     :le for c(x) ≤ 0   (single cut)
function run_kelley(; tol=1e-4, MaxIteration=1000,
                      balance_indices=nothing,
                      balance_oracle=nothing,
                      balance_kind=:eq)
    t_start = time()
    k  = 1
    x1 = copy(x_lb)
    f1, g1 = functionAndGradient(x1)

    x_best = copy(x1)
    LB = [-1.0e6]
    UB = [f1]
    F  = [f1];  G = [g1];  X = [x1]

    model = Model(HiGHS.Optimizer)
    set_silent(model)
    @variable(model, x_lb[i] <= x[i=1:n] <= x_ub[i])
    @variable(model, θ)
    @objective(model, Min, θ)

    # Initial cut on the main objective
    @constraint(model, θ >= F[1] + G[1]' * (x .- X[1]))

    has_balance = balance_indices !== nothing && balance_oracle !== nothing

    # Helper: add an epigraph cut for a single index at a given iterate
    add_balance_cut! = (idx, x_ref) -> begin
        v, gv, j = balance_oracle(x_ref, idx)
        @constraint(model, x[j] >=  v + gv' * (x .- x_ref))
        if balance_kind == :eq
            @constraint(model, x[j] >= -v - gv' * (x .- x_ref))
        end
    end

    # Initial cuts at x1
    if has_balance
        for idx in balance_indices
            add_balance_cut!(idx, x1)
        end
    end

    while (UB[end] - LB[end] > tol) && (k < MaxIteration)
        k += 1
        optimize!(model)
        x_k      = value.(x)
        θ_k      = objective_value(model)
        f_k, g_k = functionAndGradient(x_k)

        push!(LB, θ_k)
        if f_k < UB[end]; x_best = copy(x_k); end
        push!(UB, min(UB[end], f_k))

        println("k=$(lpad(k,4))  x_k=$(round.(x_k,digits=5))  LB=$(round(θ_k,digits=6))  UB=$(round(UB[end],digits=6))  gap=$(round(UB[end]-LB[end],digits=6))")

        push!(F, f_k); push!(G, g_k); push!(X, x_k)
        @constraint(model, θ >= F[end] + G[end]' * (x .- X[end]))

        if has_balance
            for idx in balance_indices
                add_balance_cut!(idx, x_k)
            end
        end
    end

    save_outputs(X, F, G, LB, UB, x_best, k, time()-t_start, "kelley")
end

# ── Subgradient algorithm (TODO) ────────────────────────────────
function run_subgradient(; tol=1e-4, MaxIteration=1000)
    # TODO: implement projected subgradient method
    # Outline:
    #   1. x1 = copy(x_lb); f1, g1 = functionAndGradient(x1); UB = f1; x_best = x1
    #   2. For k = 1, ..., MaxIteration:
    #        a. Gradient step:   y       = x_k - α_k * g_k
    #        b. Project onto X:  x_{k+1} = clamp.(y, x_lb, x_ub)
    #        c. f_{k+1}, g_{k+1} = functionAndGradient(x_{k+1})
    #        d. UB = min(UB, f_{k+1}); update x_best if improved
    #        e. Step size: e.g. α_k = α₀/√k  or Polyak step
    #   3. No clean lower bound — LB stays at -1e6
    #   4. Call save_outputs(..., "subgradient") when done
    error("Subgradient method not yet implemented")
end

# ── Dispatch ─────────────────────────────────────────────────────
if alg in ("kelley", "both")
    run_kelley(balance_indices = balance_indices,
               balance_oracle  = balance_oracle,
               balance_kind    = balance_kind)
end
if alg in ("subgradient", "both"); run_subgradient(); end



